global:
  domain: argocd.127.0.0.1.nip.io
configs:
  # Argo CD will generate a random password
  # You can retrieve it with: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
  cm:
    application.resourceTrackingMethod: annotation
    timeout.reconciliation: 60s
  params:
    "server.insecure": true
server:
  ingress:
    enabled: true
    ingressClassName: nginx
  extraArgs:
    - --insecure
